
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding.x = 18
padding.y = 18
decorations = "none"
# Uncomment one of these for background opacity:
# opacity = 0.60
# opacity = 0.92

[font]
size = 8.4

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[cursor]
style = "Block"
unfocused_hollow = true



[general]
live_config_reload = true
# Import theme colors (from theme.toml)
import = [
    "~/.config/alacritty/theme.toml"
]

