# Catppuccin Mocha theme for Alacritty

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.search]
matches = { foreground = "#1E1E2E", background = "#87B0F9" }
focused_match = { foreground = "#1E1E2E", background = "#CBA6F7" }

[colors.hints]
start = { foreground = "#1E1E2E", background = "#F9E2AF" }
end = { foreground = "#1E1E2E", background = "#74C7EC" }

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#CDD6F4"
background = "#181825"

[colors.normal]
black = "#43465A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#87B0F9"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#CDD6F4"

[colors.bright]
black = "#43465A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#87B0F9"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A1A8C9"
