#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #15130c
foreground            #e7e2d5
selection_foreground  #d5c871
selection_background  #373100
cursor                #d5c871
cursor_text_color     #15130c

# Regular Colors
color0  #15130c               
color1  #ffb4ab                 
color2  #d5c871               
color3  #a7d0b7              
color4  #f2e48a  
color5  #ebe3bd
color6  #cec7a2             
color7  #e7e2d5            

# Bright Colors
color8  #3b3930         
color9  #ffb4ab                  
color10 #d5c871                
color11 #a7d0b7               
color12 #f2e48a   
color13 #ebe3bd 
color14 #cec7a2              
color15 #e7e2d5             
