#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                


# Core Colors
background            #19120c
foreground            #efe0d6
selection_foreground  #ffb77d
selection_background  #4d2600
cursor                #ffb77d
cursor_text_color     #19120c

# Regular Colors
color0  #19120c               
color1  #ffb4ab                 
color2  #ffb77d               
color3  #c5cb96              
color4  #ffdcc3  
color5  #ffdcc3
color6  #e3c0a6             
color7  #efe0d6            

# Bright Colors
color8  #413731         
color9  #ffb4ab                  
color10 #ffb77d                
color11 #c5cb96               
color12 #ffdcc3   
color13 #ffdcc3 
color14 #e3c0a6              
color15 #efe0d6             
