#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = /home/kriahna/Pictures/Wallpapers/cats.jpg


$foreground = rgba(efe0d6ff)
$background = rgba(19120cff)

$color0 = rgba(19120cff)
$color1 = rgba(6c3a07ff)
$color2 = rgba(5a422eff)
$color3 = rgba(454a21ff)
$color4 = rgba(ffb4abff)
$color5 = rgba(ffb77dff)
$color6 = rgba(e3c0a6ff)
$color7 = rgba(efe0d6ff)
$color8 = rgba(413731ff)
$color9 = rgba(6c3a07ff)
$color10 = rgba(5a422eff)
$color11 = rgba(454a21ff)
$color12 = rgba(ffb4abff)
$color13 = rgba(ffb77dff)
$color14 = rgba(e3c0a6ff)
$color15 = rgba(efe0d6ff)
