#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                                    



# Image Path
$image = /home/kriahna/Pictures/Wallpapers/Gruvbox/moh.png


$foreground = rgba(e7e2d5ff)
$background = rgba(15130cff)

$color0 = rgba(15130cff)
$color1 = rgba(4f4700ff)
$color2 = rgba(4c472bff)
$color3 = rgba(294e3bff)
$color4 = rgba(ffb4abff)
$color5 = rgba(d5c871ff)
$color6 = rgba(cec7a2ff)
$color7 = rgba(e7e2d5ff)
$color8 = rgba(3b3930ff)
$color9 = rgba(4f4700ff)
$color10 = rgba(4c472bff)
$color11 = rgba(294e3bff)
$color12 = rgba(ffb4abff)
$color13 = rgba(d5c871ff)
$color14 = rgba(cec7a2ff)
$color15 = rgba(e7e2d5ff)
