# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Environment Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# HYPRCURSOR didn't work for some reason so i'm using xcursor
env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,33
